def show_map():
    print()
    print('  N ')
    print('W + E')
    print('  S ')
    print('----------------------------------------------')
    print('|                     |                      |')
    print('|      briefing       |                      |')
    print('|        room         |       quarters       |')
    print('|                     |                      |')
    print('----------------------|-----------------------')
    print('|                     |                      |')
    print('|                     |                      |')
    print('|       hangar        |       cafeteria      |')
    print('|                     |                      |')
    print('----------------------------------------------')

def show_secret_map():
    print()
    print('  N ')
    print('W + E')
    print('  S ')
    print('------------------------------------------------------')
    print('|       |                     |                      |')
    print('|   ?   |      briefing       |                      |')
    print('|       |        room         |       quarters       |')
    print('|       |                     |                      |')
    print('------------------------------|-----------------------')
    print('        |                     |                      |')
    print('        |                     |                      |')
    print('        |       hangar        |       cafeteria      |')
    print('        |                     |                      |')
    print('        ----------------------------------------------')
